Add !8ball parser
ServiceNowDevProgram/SlackerBot pull request #116
Opened 2022-10-04 17:21 UTC by GauthamBellamkonda

Fixes #80

2022-10-04 23:23 UTC, DavidArthurCole approved these changes

2022-10-05 16:08 UTC, earlduque requested changes

2022-10-05 16:08 UTC, earlduque commented on Parsers/Give a Magic 8 answer.js
> +var send_chat = new x_snc_slackerbot.Slacker().send_chat(current, randMagic8, current.thread_ts);
param 3 should be true or false only (boolean)
true if it should always be sent to thread
false if it should appear whereever the command is

2022-10-05 16:48 UTC, earlduque approved these changes

2022-10-05 16:48 UTC, merged