Create Ask for more details.js
ServiceNowDevProgram/SlackerBot pull request #132
Opened 2022-10-05 20:46 UTC by mjonssonme

In the spirit of :trebek we also need to be able to ask for more information, using !huh

2022-10-05 23:36 UTC, earlduque requested changes
@mjonssonme Hey Mattias, before I approve this, can you remove the irrelevant files that do not pertain to this PR? Additionally, if you meant it to be in the spirit of +:trebek: did you want to change the template to match a `react parser` instead of a `chat` parser? Check out the trebek parser's file headers to see what I mean

2022-10-05 23:36 UTC, earlduque commented on .vscode/settings.json
> +{
remove this from PR

2022-10-05 23:36 UTC, earlduque commented on Parsers/Give a Magic 8Ball reaction.js
> +/*
remove this from PR

2022-10-05 23:36 UTC, earlduque commented on Parsers/Ask for more details.js
> +/*
If this is supposed to be a react parser then all you need is
```js
/*
emoji:huh
*/

2022-10-06 06:14 UTC, mjonssonme commented on Parsers/Give a Magic 8Ball reaction.js
> +/*
done

2022-10-06 17:39 UTC, earlduque approved these changes

2022-10-06 17:40 UTC, merged