Add !quiz command
ServiceNowDevProgram/SlackerBot pull request #360
Opened 2024-10-05 18:35 UTC by isaac-vicentini

### Description:

A new command has been created that can be triggered using !quiz + servicenow theme.
This command creates a quiz from questions generated by the integration with Openai.
The user can select an answer and will receive feedback.

### Modified files:

**Parsers/Create a new SN Quiz.js**
This file is responsible for integrating with Openai and generating quiz alternatives using the Slack Block Kit.

**Scripted Rest API: SlackerBot Event Handler**
A block of code was inserted to capture user interaction with the quiz and provide feedback to the user.
Important: Code that already existed is executed with priority and has not been modified.

**Script Include Slacker**
A new function has been added to update a Slack message via rest integration. It is used to apply style to the quiz answer block, but can be used by any developer as needed.

**Result:**

![image](https://github.com/user-attachments/assets/18317539-dece-428f-8425-4883de11fcd1)

2024-10-05 19:31 UTC, earlduque commented
Whoa cool. Thanks for the cool contributin @isaac-vicentini 
Since it modifies the application files it will take us a little bit more time to validate and merge. Thank you for your patience. I'll try to work on it early next week

2024-10-05 21:08 UTC, isaac-vicentini commented
No problem @earlduque! I'll be online if needs any changes :)

2024-10-07 12:18 UTC, SapphicFire requested changes
Hi there! Like Earl has said, awesome PR. I love the idea and work you've put in. I think we have an opportunity to look at extending the interactivity support inline with what you've started here for these buttons, and am excited to add this in.

I've added some feedback, just hoping for some clarity on some key details and potentially some updates per those comments.

2024-10-07 23:24 UTC, isaac-vicentini commented
> Hi there! Like Earl has said, awesome PR. I love the idea and work you've put in. I think we have an opportunity to look at extending the interactivity support inline with what you've started here for these buttons, and am excited to add this in.
> 
> I've added some feedback, just hoping for some clarity on some key details and potentially some updates per those comments.

Hi @SapphicFire!

Thanks for the feedback, I will analyze the comments and let you know about improvements.

2024-10-07 23:35 UTC, isaac-vicentini commented on Parsers/Create a new SN Quiz.js
> +            "model": "gpt-4",
Considering that Servicenow products are constantly evolving, I believe that `gpt-4o` is more suitable because it is more up-to-date

2024-10-07 23:37 UTC, isaac-vicentini commented on b02cf9e61b861d10d806dc23b24bcb3f/update/sys_ws_operation_bbcb42a61bc61d10d806dc23b24bcbd2.xml
> +        var slacker = new x_snc_slackerbot.Slacker();
Of course, there is no need to instantiate twice

2024-10-07 23:47 UTC, isaac-vicentini commented on b02cf9e61b861d10d806dc23b24bcb3f/update/sys_ws_operation_bbcb42a61bc61d10d806dc23b24bcbd2.xml
> +            slacker.send_chat(current, incorrectMessage, false);
Indeed, it could turn into a lot of spam messages. I will analyze if it is possible to limit the response to the user who asked

2024-10-07 23:50 UTC, isaac-vicentini commented on Parsers/Create a new SN Quiz.js
> +                "type": "section",
Yes, we don’t want to cause any confusion for the user :)

2024-10-09 22:47 UTC, isaac-vicentini commented
Hi @SapphicFire!

I’ve made 2 new commits on the same branch, implementing the changes we discussed.
I believe it’s now a more robust and complete functionality for use :)

2024-10-10 05:12 UTC, SapphicFire requested changes
Thanks for the fixes so far. There is one item I missed that will be rather important for us to address prior to merging this PR.

2024-10-10 05:12 UTC, SapphicFire commented on b02cf9e61b861d10d806dc23b24bcb3f/update/sys_ws_operation_bbcb42a61bc61d10d806dc23b24bcbd2.xml
> -		//gs.info('slackoff: ' + (request.body.dataString));
While I totally agree with removing the comment call, removing the return for bot-messages will open up recursive triggers for payloads from the bot.

Can you please re-introduce this? If it was blocking functionality, let us know and we can brainstorm an updated approach

2024-10-15 18:44 UTC, isaac-vicentini commented
Hi @SapphicFire!

I’m a beginner here on GitHub and I have a question:
Should I be the one to Resolve Conflicts?

![image](https://github.com/user-attachments/assets/cb59f2ca-4eef-4518-a15e-b9a995ee523e)

I believe it is from a file that is automatically updated.

2024-10-18 09:56 UTC, SapphicFire commented
> Hi @SapphicFire!
> 
> I’m a beginner here on GitHub and I have a question: Should I be the one to Resolve Conflicts?

This depends on the scenario. We always encourage developers to learn this process if they want to, and if they haven't forked from the repo recently, that can be part of what causes it and so we sometimes ask for them to sync their fork and then implement the changes to avoid that. But in the case of these checksum files, we are happy to handle those

2024-10-19 02:33 UTC, merged

2024-10-19 15:44 UTC, isaac-vicentini commented
Hi @SapphicFire!

The interaction component is not working as expected when testing on the main branch