World Time.js
ServiceNowDevProgram/SlackerBot pull request #366
Opened 2024-10-07 06:05 UTC by ankitshu

This parser will provide users with the current time in a specified city using the !time [city] command. It will call the 'worldtimeapi' API and respond with the local time for the specified city

2024-10-07 08:10 UTC, ashu759 requested changes
Readme file is missing again here. I checked and it is needed. Can you please add it.

2024-10-07 13:54 UTC, ashu759 approved these changes
So for slacker bot the readme is not needed. Hence approved.

2024-10-07 13:55 UTC, ashu759 commented
Looks good

2024-10-07 14:01 UTC, SapphicFire requested changes
It appears that this contribution is a duplicate of the `What time is it.js` parser. Please review this parser and look to incorporate or extend its functionality where appropriate as opposed to introducing a duplicate function.

2024-10-08 12:58 UTC, SapphicFire commented
Thank you for your contribution. However, it seems that the changes in this Pull Request are duplicating existing functionality. Please review the existing parser and ensure that you can expand and incorporate the functionality in this parser. Closing this for now. Once you make additional changes, feel free to re-open this Pull Request or create a new one.

2024-10-08 12:58 UTC, closed without merging