Basic Math Parser.js
ServiceNowDevProgram/SlackerBot pull request #373
Opened 2024-10-07 15:27 UTC by ynr-ram

The Basic Math Parser enables users to perform simple addition calculations directly within the chat interface by entering commands like !add 5 10. It captures the two numbers provided in the command, computes their sum, and returns the result to the user in a friendly format. This parser enhances user interaction by allowing quick calculations without the need for external tools or applications.

2024-10-07 19:30 UTC, earlduque requested changes
Several of your recent pull requests are getting into the realm of spam, please be more thoughtful about your contributions

2024-10-07 19:30 UTC, earlduque commented on Parsers/Basic Math Parser.js
> +regex: !add (\d+) (\d+)
this regex already conflicts with another one of your pull requests.

2024-10-07 19:30 UTC, earlduque commented on Parsers/Basic Math Parser.js
> +    var num1 = parseInt(matches[1], 10);
there are many more ways this can be implemented without being so restrictive on how it works

2024-10-09 13:01 UTC, SapphicFire commented
Thank you for your submission. However, there are outstanding changes required before we can approve this parser. Please consider alternative solutions that make this parser robust and extensible.

Please complete your contribution by adding the necessary elements and resubmit or update this pull request for further review. Closing this for now. Once you make additional changes, feel free to re-open this Pull Request or create a new one.

2024-10-09 13:01 UTC, closed without merging