Create fetch IP Address Information.js
ServiceNowDevProgram/SlackerBot pull request #425
Opened 2024-10-22 11:49 UTC by Pradeep567iaf

/*
File: fetch IP Address Information.js

Description: This script extracts an IP address from user input, validates the format, and retrieves geographic and network details (e.g., city, region, country, ISP) using the ipinfo.io API. The result is then sent back to the user via a chat interface. If the input is invalid, it returns an error message. 

Activation Example: Triggered by the command "!ipinfo" followed by an IP address. */

2024-10-22 13:37 UTC, wiz0floyd requested changes

2024-10-22 13:37 UTC, wiz0floyd commented on Parsers/fetch IP Address Information.js
> +        var ipInformationString = JSON.stringify(ipInfomation); // Covert the object to string
Could you do some formatting for slack mark down instead of sending json?

2024-10-26 11:43 UTC, SapphicFire commented
Thank you for your contribution. As it has been several days since you have been provided feedback and had changes requested, I will close this PR. Please review the files you have changed/added and ensure that all modifications are correct, valid, and align with the project’s goals and guidelines. Closing this for now. Once you make additional changes, feel free to re-open this Pull Request or create a new one.

2024-10-26 11:43 UTC, closed without merging

2024-10-28 05:04 UTC, Pradeep567iaf commented
Hello Astrid Sapphire , I will make the change as per advice.
Best regards,
Pradeep

On Sat, Oct 26, 2024 at 5:13 PM Astrid Sapphire ***@***.***>
wrote:

> Closed #425 <https://github.com/ServiceNowDevProgram/SlackerBot/pull/425>.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ServiceNowDevProgram/SlackerBot/pull/425#event-14900936343>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AOLZKKLIXPUMZKVFMBW2DBDZ5N57ZAVCNFSM6AAAAABQMJX5EWVHI2DSMVQWIX3LMV45UABCJFZXG5LFIV3GK3TUJZXXI2LGNFRWC5DJN5XDWMJUHEYDAOJTGYZTIMY>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***
> com>
>