Added weeMoji script and Enhance README.md with WeekMoji Script Details
ServiceNowDevProgram/SlackerBot pull request #430
Opened 2024-10-24 17:44 UTC by prynacshrma

Summary
This pull request updates the `README.md` file to include detailed information about the newly added `weekMoji` script. The changes aim to provide users with an understanding of the script's functionality, usage, and examples.

Changes Made
- Added a section on the `weekMoji` script, including:
  - Overview of the script’s purpose
  - Instructions on how to use the script
  - Examples of the output generated by the script

Benefits
These updates will help users better understand how to utilize the `weekMoji` script effectively, enhancing their experience with the Slackerbot project.

2024-10-24 17:49 UTC, wiz0floyd requested changes

2024-10-24 17:49 UTC, wiz0floyd commented on wMoji
> +regex:<@U.*>
This trigger will be very spammy.

2024-10-24 17:49 UTC, wiz0floyd commented on emojis_for_weekdays
> +regex:<@U.*>
This trigger will cause spam.

2024-10-24 17:49 UTC, wiz0floyd commented on wMoji
Duplicate?

2024-10-24 17:49 UTC, wiz0floyd commented on README.md
The top level readme file is for the whole bot. Individual parsers do not require a readme. Please review the contributing requirements for this repository.

2024-10-24 17:49 UTC, closed without merging

2024-10-24 18:07 UTC, prynacshrma commented on wMoji
> +regex:<@U.*>
changed it

2024-10-25 00:14 UTC, wiz0floyd commented
Hi there! I see you marked my comments as resolved, but didn't see any new commits to this branch. Please let me know if you need help with GitHub.